name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2

            - name: Install packages
              run: npm i
            
            - name: Generate README
              run: node index.js

            - name: Deploy
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: ./README.md
                  commit-msg: Update README
                  github-token: ${{ secrets.GITHUB_TOKEN }}